#!/bin/sh
#
# Copyright 2017 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

# Write out new trusted keys in the chroot.

# Expects the build id as the first argument, and key material on stdin.

set -e

SUDO=/usr/bin/sudo
CHROOT=/usr/sbin/chroot

BUILDID="$1"
ROOT="$HOME/build-$BUILDID/chroot-autobuild"

cd $HOME
cd "$ROOT/etc/apt"

echo "Adding trusted keys to build-$BUILDID"

$SUDO $CHROOT $ROOT apt-key add -
$SUDO $CHROOT $ROOT apt-key list
