#!/bin/sh
#
# Copyright 2009 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

# Buildd Slave tool to update a debian chroot

# Expects build id as arg 1, makes build-id to contain the build

# Needs SUDO to be set to a sudo instance for passwordless access

SUDO=/usr/bin/sudo
CHROOT=/usr/sbin/chroot
APTGET=/usr/bin/apt-get
BUILDID="$1"
ARCHITECTURETAG="$2"
ROOT=$HOME/build-$BUILDID/chroot-autobuild
OPTIONS="-o DPkg::Options::=--force-confold"

set -e

exec 2>&1

echo "Updating debian chroot for build $BUILDID"

hostarch=$(dpkg --print-architecture)

case $hostarch in
  hppa|powerpc|sparc)
    CHROOT="linux32 $CHROOT"
    ;;
  amd64)
    case "$ARCHITECTURETAG" in
      i386|lpia)
        CHROOT="linux32 $CHROOT"
        ;;
    esac
    ;;
esac

# Anything more fancy than amd64->ia32 is done with qemu+syscall
# emulation, handled via binfmt.misc hints to the kernel that require
# the statically-compiled qemu binary to appear in the same place both
# inside and outside the chroot.
if [ "$hostarch" != "$ARCHITECTURETAG" ]
then
  case "$hostarch" in
    i386|amd64|lpia)
      case "$ARCHITECTURETAG" in
        arm*)
          $SUDO /usr/bin/install /usr/bin/qemu-arm-static $ROOT/usr/bin/
          ;;
      esac
      ;;
  esac
fi

export LANG=C
export DEBIAN_FRONTEND=noninteractive
export TTY=unknown

$SUDO $CHROOT $ROOT $APTGET -uy update < /dev/null
$SUDO $CHROOT $ROOT $APTGET $OPTIONS -uy --purge dist-upgrade < /dev/null

